metaG_accession: axial_metaG
metaT_accession: axial_metaT
metaG_ena_table: /vortexfs1/omics/huber/shu/axial/axial-seamount-euks/input/axial_metaG-10302019.txt
metaT_ena_table: /vortexfs1/omics/huber/shu/axial/axial-seamount-euks/input/axial_metaT-10302019.txt

# Input dir changed to location of trimmed files
inputDIR: /vortexfs1/omics/huber/shu/axial/trimmed
outputDIR: /vortexfs1/omics/huber/shu/axial/snake-output-10302019
scratch:  /vortexfs1/scratch/sarahhu/axial-assemble-only

adapters: input/adapters/illumina-adapters.fa
metaG_sample_list: /vortexfs1/omics/huber/shu/axial/axial-seamount-euks/input/axial_metaG_Assembly_List-10302019.txt
metaT_sample_list: /vortexfs1/omics/huber/shu/axial/axial-seamount-euks/input/axial_metaT_Assembly_List-10302019.txt

megahit_other: --continue --k-list 29,39,59,79,99,119 
megahit_cpu: 80
megahit_min_contig: 1000
megahit_mem: .95
restart-times: 0
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
rerun-incomplete: true
keep-going: true
